import {notFound} from "next/navigation";import {Brand} from "@/components/Brand";import {Notice,RiskPill} from "@/components/Ui";import {one} from "@/db";import {INSTRUMENTS} from "@/lib/instruments";import {CONSENT_VERSION,issueCsrf,sha256} from "@/lib/security";import type {ScoreResult} from "@/lib/types";
export const dynamic="force-dynamic";type Participant={id:string;participant_code:string;instrument_form:"A"|"B";status:string;campaign_name:string;campaign_status:string;organization_name:string;results_json:string|null};
export default async function EvaluationPage({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{error?:string;completed?:string}>}){const{token}=await params;const query=await searchParams;if(!/^[A-Za-z0-9_-]{40,100}$/.test(token))notFound();const tokenHash=await sha256(token);const participant=await one<Participant>(`SELECT participants.id,participants.participant_code,participants.instrument_form,participants.status,campaigns.name AS campaign_name,campaigns.status AS campaign_status,organizations.name AS organization_name,submissions.results_json FROM participants JOIN campaigns ON campaigns.id=participants.campaign_id JOIN organizations ON organizations.id=campaigns.organization_id LEFT JOIN submissions ON submissions.participant_id=participants.id WHERE participants.invite_token_hash=?`,tokenHash);if(!participant)notFound();const result=participant.results_json?JSON.parse(participant.results_json) as ScoreResult:null;
 if(participant.status==="completed"&&result)return <main className="assessment-shell"><header className="assessment-header"><Brand/><span>Respuesta protegida</span></header><section className="completion-card"><span className="completion-check">✓</span><p className="eyebrow">Evaluación completada</p><h1>Gracias por participar</h1><p>Tu respuesta quedó registrada y el enlace ya no admite cambios.</p><div className="personal-result"><small>Resultado tecnológico demostrativo</small><strong>{result.total.score} / 100</strong><RiskPill level={result.total.risk.key} label={result.total.risk.label}/></div><Notice tone="warning">Este resultado usa preguntas y cortes de demostración. No es un diagnóstico ni debe orientar decisiones laborales.</Notice></section></main>;
 if(participant.campaign_status!=="active")return <main className="assessment-shell"><header className="assessment-header"><Brand/><span>Acceso protegido</span></header><section className="completion-card"><span className="centered-icon">i</span><p className="eyebrow">Campaña no disponible</p><h1>La evaluación no está activa</h1><p>Consulta con la persona responsable para confirmar las fechas de aplicación.</p></section></main>;
 const instrument=INSTRUMENTS[participant.instrument_form];const csrf=await issueCsrf(tokenHash,`evaluate:${participant.id}`,120);const grouped=Object.entries(instrument.domains).map(([key,label])=>({key,label,questions:instrument.questions.filter(q=>instrument.dimensions.find(d=>d.key===q.dimension)?.domain===key)}));
 return <main className="assessment-shell"><header className="assessment-header"><Brand/><span>Forma {instrument.form} · Código {participant.participant_code}</span></header><section className="assessment-intro"><div><p className="eyebrow">{participant.organization_name}</p><h1>{participant.campaign_name}</h1><p>Lee cada enunciado y elige la opción que mejor represente tu percepción actual.</p></div><div className="assessment-meta"><strong>{instrument.questions.length}</strong><span>preguntas demo</span></div></section>{query.error&&<Notice tone="danger">{query.error}</Notice>}<Notice tone="warning"><strong>Entorno demostrativo.</strong> {instrument.notice}</Notice>
 <form className="assessment-form" action="/api/evaluate" method="post"><input type="hidden" name="token" value={token}/><input type="hidden" name="csrf" value={csrf}/><input type="hidden" name="consentVersion" value={CONSENT_VERSION}/><section className="consent-card"><div><span>⌁</span><div><h2>Consentimiento informado</h2><p>Participar es voluntario. La aplicación usa un código seudónimo, registra el consentimiento y protege reportes de grupos pequeños.</p></div></div><label className="consent-check"><input type="checkbox" name="consent" value="accepted" required/><span>Acepto participar y autorizo el tratamiento de mis respuestas para esta prueba tecnológica.</span></label></section>
 {grouped.map((group,i)=><section className="question-section" key={group.key}><div className="question-section-title"><span>{String(i+1).padStart(2,"0")}</span><div><p>Dominio</p><h2>{group.label}</h2></div></div>{group.questions.map((q,j)=><fieldset className="question" key={q.id}><legend><span>{j+1}</span>{q.text}</legend><div className="option-grid">{instrument.options.map(o=><label key={o.value}><input type="radio" name={`q_${q.id}`} value={o.value} required/><span>{o.label}</span></label>)}</div></fieldset>)}</section>)}<section className="submit-card"><div><strong>Revisa antes de enviar</strong><p>Después del envío no podrás modificar las respuestas.</p></div><button className="button button-primary" type="submit">Enviar evaluación →</button></section></form><footer className="assessment-footer">BRPS 2026 · Privacidad por diseño · {CONSENT_VERSION}</footer></main>;
}
