import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { EmptyState, Notice, PageHeader, RiskPill, StatusPill } from "@/components/Ui";
import { all, one } from "@/db";
import { canManage, canViewIndividual, hasOrganizationAccess, requireAuthorizedUser } from "@/lib/auth";
import { formatDate, formatDateTime } from "@/lib/format";
import { ROLE_LEVELS } from "@/lib/instruments";
import { issueCsrf } from "@/lib/security";
import type { ScoreResult } from "@/lib/types";
export const dynamic="force-dynamic";
type Campaign={id:string;organization_id:string;organization_name:string;name:string;description:string;status:string;starts_on:string|null;ends_on:string|null};
type Participant={id:string;participant_code:string;instrument_form:"A"|"B";status:string;created_at:string;submission_id:string|null;completed_at:string|null;results_json:string|null};

export default async function CampaignDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{invite?:string;created?:string;error?:string;updated?:string}>}){
 const {id}=await params;const query=await searchParams;const user=await requireAuthorizedUser(`/campanas/${id}`);const campaign=await one<Campaign>(`SELECT campaigns.*,organizations.name AS organization_name FROM campaigns JOIN organizations ON organizations.id=campaigns.organization_id WHERE campaigns.id=?`,id);if(!campaign||!hasOrganizationAccess(user,campaign.organization_id))notFound();
 const participants=await all<Participant>(`SELECT participants.*,submissions.id AS submission_id,submissions.completed_at,submissions.results_json FROM participants LEFT JOIN submissions ON submissions.participant_id=participants.id WHERE participants.campaign_id=? ORDER BY participants.created_at DESC`,id);const completed=participants.filter(p=>p.status==="completed").length;const completion=participants.length?Math.round(completed/participants.length*100):0;
 const participantCsrf=canManage(user)?await issueCsrf(user.email,`participant:create:${id}`):"";const statusCsrf=canManage(user)?await issueCsrf(user.email,`campaign:status:${id}`):"";let inviteUrl="";if(query.invite){const h=await headers();const host=h.get("host");inviteUrl=host?`${h.get("x-forwarded-proto")||"https"}://${host}/evaluar/${query.invite}`:`/evaluar/${query.invite}`;}
 return <AppShell user={user}><PageHeader eyebrow={campaign.organization_name} title={campaign.name} description={campaign.description||"Gestión de participantes, aplicación y resultados."} action={<><Link className="button button-secondary" href={`/reportes/${id}`}>Ver reporte</Link><a className="button button-primary" href={`/api/admin/campaigns/${id}/export`}>Exportar CSV</a></>}/>
 {query.created&&<Notice tone="success">Campaña creada. Actívala cuando esté lista para recibir respuestas.</Notice>}{query.updated&&<Notice tone="success">Estado actualizado correctamente.</Notice>}{query.error&&<Notice tone="danger">{query.error}</Notice>}{inviteUrl&&<div className="notice notice-success"><strong>Invitación creada.</strong> Copia ahora este enlace: se muestra una sola vez.<div className="code-box" style={{marginTop:".7rem"}}><label htmlFor="invite-url">Enlace único</label><input id="invite-url" readOnly value={inviteUrl}/></div></div>}
 <section className="card"><div className="card-body"><div className="detail-grid"><div className="detail-item"><small>Estado</small><strong><StatusPill value={campaign.status}/></strong></div><div className="detail-item"><small>Periodo</small><strong>{formatDate(campaign.starts_on)} — {formatDate(campaign.ends_on)}</strong></div><div className="detail-item"><small>Avance</small><strong>{completion}% · {completed} de {participants.length}</strong></div></div>{canManage(user)&&<form className="status-form" action={`/api/admin/campaigns/${id}/status`} method="post"><input type="hidden" name="csrf" value={statusCsrf}/><label htmlFor="campaign-status">Cambiar estado</label><select id="campaign-status" name="status" defaultValue={campaign.status}><option value="draft">Borrador</option><option value="active">Activa</option><option value="closed">Cerrada</option></select><button className="button button-secondary button-small" type="submit">Actualizar</button></form>}</div></section>
 <div className="content-grid detail-content"><section className="card"><div className="card-header"><div><h2>Participantes</h2><p>Códigos seudónimos y trazabilidad</p></div></div>{participants.length?<div className="table-wrap"><table><thead><tr><th>Código</th><th>Forma</th><th>Estado</th><th>Resultado demo</th><th>Fecha</th><th/></tr></thead><tbody>{participants.map(p=>{const result=p.results_json?JSON.parse(p.results_json) as ScoreResult:null;return <tr key={p.id}><td><strong>{p.participant_code}</strong></td><td><span className="form-badge">{p.instrument_form}</span></td><td><StatusPill value={p.status}/></td><td>{result?<RiskPill level={result.total.risk.key} label={`${result.total.score} · ${result.total.risk.label}`}/>:"—"}</td><td>{formatDateTime(p.completed_at||p.created_at)}</td><td>{p.submission_id&&canViewIndividual(user)?<Link className="table-link" href={`/resultados/${p.submission_id}`}>Detalle</Link>:""}</td></tr>})}</tbody></table></div>:<EmptyState title="Sin participantes" text="Crea el primer código de invitación desde el formulario lateral."/>}</section>
 <aside><section className="card" id="invitar"><div className="card-header"><div><h2>Nueva invitación</h2><p>Un enlace de un solo uso</p></div></div><div className="card-body">{!canManage(user)?<Notice>Tu rol no permite crear invitaciones.</Notice>:campaign.status==="closed"?<Notice tone="warning">La campaña está cerrada.</Notice>:<form className="form-grid" action="/api/admin/participants" method="post"><input type="hidden" name="csrf" value={participantCsrf}/><input type="hidden" name="campaignId" value={id}/><div className="field field-full"><label htmlFor="participant-code">Código seudónimo *</label><input id="participant-code" name="participantCode" required maxLength={40} placeholder="P-001"/><small>No uses nombre, cédula ni correo.</small></div><div className="field field-full"><label htmlFor="role-level">Nivel del cargo *</label><select id="role-level" name="roleLevel" required>{ROLE_LEVELS.map(role=><option key={role.value} value={role.value}>{role.label} · Forma {role.form}</option>)}</select></div><div className="form-actions"><button className="button button-primary button-block" type="submit">Generar enlace único</button></div></form>}</div></section></aside></div></AppShell>;
}
